app = "pillopedia"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[mounts]
  source = "pillopedia_data"
  destination = "/data"

[env]
  DATABASE_PATH = "/data/pillopedia.db"
